### ISSUE TITLE
Demo site UI checklist

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#61]
- [x] List of tabs (close)
- [x] Transform gizmo mouse alignment
- [x] Orbit controls
- [x] "No XR" enter XR button detection
- [ ] Better copy
- [ ] In-XR gizmo control (?)
- [ ] In-XR HTML UI (?)

**Comment by modulesio** [comment]
Broke out the remaining issues.
